#!/usr/bin/env perl
use strict;

sub gen_pass {
    my @symbols = ('a'...'z', 'A'...'Z', 0...9);
    my $length = shift;
    my $randpass = join "", map $symbols[rand @symbols], 1..$length;
    return $randpass;
}

sub MAIN {
    for(my $i=0;$i<$ARGV[1];$i++) {
        print gen_pass($ARGV[0]), "\n";
    }
}

MAIN;
